def twos(originx,originy):
    print(originx,originy,originx+1,originy)
    print(originx,originy+1,originx+1,originy+1)
    print(originx,originy,originx,originy+1)
    print(originx+1,originy,originx+1,originy+1)
def fours(originx,originy):
    twos(originx,originy)   
    twos(originx,originy+2) 
    twos(originx+2,originy) 
    twos(originx+2,originy+2)
    twos(originx+1,originy+1)
    twos(originx,originy)   
    twos(originx,originy+2) 
    twos(originx+2,originy) 
    twos(originx+2,originy+2)
def eights(originx,originy):
    fours(originx,originy)
    fours(originx,originy+4)
    fours(originx+4,originy)
    fours(originx+4,originy+4)
    fours(originx+2,originy+2)
    fours(originx,originy)
    fours(originx,originy+4)
    fours(originx+4,originy)
    fours(originx+4,originy+4)
def sixteens(originx,originy):
    eights(originx,originy)
    eights(originx,originy+8)
    eights(originx+8,originy)
    eights(originx+8,originy+8)
    eights(originx+4,originy+4)
    eights(originx,originy)
    eights(originx,originy+8)
    eights(originx+8,originy)
    eights(originx+8,originy+8)
n=int(input())
if n==2:
    print(4)
    twos(1,1)
elif n==4:
    print(36)
    fours(1,1)
elif n==8:
    print(324)
    eights(1,1)
elif n==16:
    print(2916)
    sixteens(1,1)
